version: '3.1'

services:
  app1:
    build: ./app
    restart: always
    environment:
      MY_IP: 127.0.0.1
      POSTGRES_DSN: "host=db port=5432 sslmode=disable user=postgres dbname=postgres password=${DB_PASSWORD}"
    ports:
      - 3000:3000

  app2:
    build: ./app
    restart: always
    environment:
      MY_IP: 127.0.0.2
      POSTGRES_DSN: "host=db port=5432 sslmode=disable user=postgres dbname=postgres password=${DB_PASSWORD}"
    ports:
      - 3001:3000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx
    restart: always
    ports:
      - 9000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db-data:
