version: '3.1'

services:
  db:
    image: postgres
    restart: always
    network_mode: host
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
